nguage: python
python:
  - "3.5"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_install:
  - sudo pip3 install -U pip
install:
  - sudo pip3 install -r requirements.txt
script:
  - python3 -m pytest tests
