nguage: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_install:
  - sudo pip3 install --allow-all-external -U pip
install:
  - sudo pip3 install --allow-all-external -r requirements.txt
script:
  - python3 -m pytest tests
